#!/usr/bin/env python3
"""Regenerate the directed-ablation table (tab:directed_ablation) from JSON.

Reads ``results/controlled/directed_ablation/analysis.json`` (produced by
``scripts/controlled/controlled_directed_ablation.py``) and emits both a LaTeX
table body and a Markdown summary so the paper table is always traceable to the
underlying statistics (mean Δacc, 95% bootstrap CI, paired-t p, Wilcoxon p,
Cohen's d) rather than hand-transcribed.

Usage
-----
    python scripts/reports/build_directed_ablation_table.py
    python scripts/reports/build_directed_ablation_table.py \
        --analysis results/controlled/directed_ablation/analysis.json
"""

import os
import sys
import json
import argparse

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))

# Display order + human-readable labels for the probe directions.
DIRECTION_LABELS = [
    ("violated_in_row", "Row violation"),
    ("violated_in_col", "Col violation"),
    ("violated_in_box", "Box violation"),
    ("per_cell_correct", "Correctness"),
    ("is_given", "Is given"),
]
SUBSPACE_LABELS = [
    ("subspace_2d_violated_in_row_violated_in_col", "Subspace (row+col, 2D)"),
    ("subspace_3d_violated_in_row_violated_in_col", "Subspace (row+col+box, 3D)"),
]


def pct(x):
    return 100.0 * x


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--analysis", type=str,
        default=os.path.join(REPO_ROOT, "results", "controlled",
                             "directed_ablation", "analysis.json"),
    )
    parser.add_argument("--out_dir", type=str,
                        default=os.path.join(REPO_ROOT, "results", "controlled",
                                             "directed_ablation"))
    args = parser.parse_args()

    with open(args.analysis) as f:
        A = json.load(f)

    rows = []  # (label, dacc_pct, ci_lo_pct, ci_hi_pct, p_t, p_w, d, n)
    n_puzzles = None
    rand_mean = None
    for key, label in DIRECTION_LABELS:
        if key not in A:
            continue
        e = A[key]
        pa = e["probe_delta_accuracy"]
        n_puzzles = pa.get("n", n_puzzles)
        if rand_mean is None and "random_control_delta_accuracy" in e:
            rand_mean = e["random_control_delta_accuracy"]["mean"]
        rows.append((
            label,
            pct(pa["mean"]), pct(pa["ci_lower"]), pct(pa["ci_upper"]),
            e.get("paired_p_value"), e.get("wilcoxon_p_value"),
            e.get("cohens_d"), pa.get("n"),
        ))

    sub_rows = []
    for key, label in SUBSPACE_LABELS:
        if key not in A:
            continue
        pa = A[key]["delta_accuracy"]
        sub_rows.append((label, pct(pa["mean"]), pct(pa["ci_lower"]), pct(pa["ci_upper"])))

    # ── LaTeX table body ──────────────────────────────────────────────
    latex = []
    latex.append("% Auto-generated by scripts/reports/build_directed_ablation_table.py")
    latex.append(f"% Source: {os.path.relpath(args.analysis, REPO_ROOT)}  (N={n_puzzles})")
    latex.append(r"\begin{tabular}{@{}lcccc@{}}")
    latex.append(r"\toprule")
    latex.append(r"\textbf{Direction ablated} & $\dacc$ (\%) & \textbf{95\% CI} & "
                 r"\textbf{$p$ (t / W)} & \textbf{Cohen's $d$} \\")
    latex.append(r"\midrule")
    for label, m, lo, hi, p_t, p_w, d, n in rows:
        sign = "+" if m >= 0 else ""
        latex.append(
            f"{label:16s} & ${sign}{m:.2f}$ & "
            f"$[{lo:+.2f}, {hi:+.2f}]$ & "
            f"{p_t:.3f} / {p_w:.3f} & ${d:+.3f}$ \\\\"
        )
    if rand_mean is not None:
        latex.append(r"\midrule")
        latex.append(
            f"Random controls (pooled) & ${'+' if rand_mean>=0 else ''}{pct(rand_mean):.2f}$ "
            r"& --- & --- & --- \\"
        )
    for label, m, lo, hi in sub_rows:
        sign = "+" if m >= 0 else ""
        latex.append(f"{label:16s} & ${sign}{m:.2f}$ & $[{lo:+.2f}, {hi:+.2f}]$ & --- & --- \\\\")
    latex.append(r"\bottomrule")
    latex.append(r"\end{tabular}")
    latex_str = "\n".join(latex)

    # ── Markdown summary ──────────────────────────────────────────────
    md = []
    md.append(f"# Directed ablation summary (N={n_puzzles})\n")
    md.append("| Direction | Δacc (%) | 95% CI | p (t) | p (Wilcoxon) | Cohen's d |")
    md.append("|---|---|---|---|---|---|")
    for label, m, lo, hi, p_t, p_w, d, n in rows:
        md.append(f"| {label} | {m:+.2f} | [{lo:+.2f}, {hi:+.2f}] | {p_t:.3f} | {p_w:.3f} | {d:+.3f} |")
    if rand_mean is not None:
        md.append(f"| Random controls (pooled) | {pct(rand_mean):+.2f} | — | — | — | — |")
    for label, m, lo, hi in sub_rows:
        md.append(f"| {label} | {m:+.2f} | [{lo:+.2f}, {hi:+.2f}] | — | — | — |")
    md_str = "\n".join(md) + "\n"

    os.makedirs(args.out_dir, exist_ok=True)
    tex_path = os.path.join(args.out_dir, "directed_ablation_table.tex")
    md_path = os.path.join(args.out_dir, "directed_ablation_table.md")
    with open(tex_path, "w") as f:
        f.write(latex_str + "\n")
    with open(md_path, "w") as f:
        f.write(md_str)

    print(latex_str)
    print("\n" + md_str)
    print(f"\nWrote:\n  {tex_path}\n  {md_path}")


if __name__ == "__main__":
    main()
